version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "[TASK]"
    ignore:
      - dependency-name: "jquery"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tinymce"
        update-types: ["version-update:semver-major"]
